version: '3.8'


services:

  mariadb:
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mariadb       # nombre exacto de tu servicio MariaDB
      PMA_PORT: 3306          # puerto REAL dentro del contenedor (no el expuesto)
      PMA_ARBITRARY: 1        # permite conectarse a otros hosts si quieres

volumes:
  mariadb_data: